# Generated by Django 6.0.1 on 2026-01-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_discription_image_description_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publicated',
            field=models.BooleanField(default=False),
        ),
    ]
