# Generated by Django 6.0.1 on 2026-01-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_publicated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='publicated',
            new_name='published',
        ),
    ]
