# Generated by Django 6.0.1 on 2026-01-21 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_publicated_image_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
